### ISSUE TITLE
Starting Items tab doesn't update when settings change the starting items

### ISSUE THREAD

**Issue by matthewkirby** [OoTMM/gui#6]
To reproduce, click over to the starting items tab, then click over to progressive items and change any of the options there. Then return to the starting items and see that the changed progressive did not update. If you then refresh the page, the starting items tab updates.

I expect it has to do with react's render function not updating hidden content when setState is called on the progressive items tab. It may be easily fixed by calling a render when the tab is shown? Could potentially work by changing the active gui tab to a state variable?

Obviously not super high priority, but put it here so it didn't get buried in the discord channel.

**Comment by Nax** [comment]
Fixed (a while ago)
